services:
  frontend-service:
    container_name: frontend-container
    image: staticwebapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - msma_network


networks:
  msma_network:
    external: true